version: '3'
services:
    db:
      image: mysql
      container_name: mysql-server
      environment:
        MYSQL_DATABASE: 'udemy_compras'
        MYSQL_USER: 'admin'
        MYSQL_PASSWORD: 'admin'
        MYSQL_ROOT_PASSWORD: 'root'
      ports:
        - '3306:3306'
      expose:
        - '3306'
      volumes:
          - microservice-mysql:/var/lib/mysql
volumes:
  microservice-mysql: